version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fastapi_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=66f3f58cb1210164f47909106190eef336f38224adb69018b98337089df159de
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - JWT_ALGORITHM=HS256
      - HTTP_MAX_ATTEMPTS=5
      - HTTP_ATTEMPT_COOLDOWN=60
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_ORDER=orders_event
      - KAFKA_TOPIC_SALES=sales_event
      - KAFKA_GROUP_ID=forsit_group
      - REDIS_INCOMING_ORDER=CHANNEL_INCOMING_ORDER
      - REDIS_LOW_INVENTORY=REDIS_LOW_INVENTORY
      - REDIS_QUEUE_ORDER=REDIS_QUEUE_ORDER
    networks:
      - kafka-network

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_db
    ports:
      - "5432:5432"
    networks:
      - kafka-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kafka-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0"
    networks:
      - kafka-network

volumes:
  postgres_data:
  redis_data:

networks:
  kafka-network:
    driver: bridge